# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
# docs https://jekyllrb.com/docs/

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: matheusmbar-github-io
google_analytics: UA-134810563-1
title: Matheus Marques


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Matheus Marques

description: A journey about developing embedded systems
author:
  name: Matheus Marques
#  email: 
  github: matheusmbar
#  twitter: 
#  pinterest: 
  linkedin: matheusmbar
#  bio: 
  email_md5: 8db7b9f2f6186cfad394d87fe6868a83
  bio: I'm an Electronic Engineer always trying to learn more about developing embedded systems and help other people to do so

excerpt_separator: <!--more-->
#rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
