# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
# docs https://jekyllrb.com/docs/

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: matheusmbar-github-io
google_analytics: UA-134810563-1
google_tagmanager: "GTM-5G8JWVF"
title: Matheus Marques
logo: assets/media/MM_logo_300x218.png
logo-square: assets/media/MM_logo_300x300.png
logo-share: assets/media/MM_logo_190x190.png

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: matheusmbar
      social-share: true # add social media sharing buttons to all blog posts

description: A journey about developing embedded systems
author:
  name: Matheus Marques
  email: mail@matheusmbar.com
  github: matheusmbar
#  twitter:
#  pinterest:
  linkedin: matheusmbar
  profile_pic: "assets/profiles/matheus.jpg"
#  bio:
  email_md5: 8db7b9f2f6186cfad394d87fe6868a83
  bio: I'm an Electronic Engineer always trying to learn more about developing embedded systems and help other people to do so

excerpt_separator: <!--more-->
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
enable_analytics: true

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  reddit: true

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

url: "https://matheusmbar.com" # the base hostname & protocol for your site

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-seo-tag